# В этом модуле описывается функция, которая принимает в качестве аргумента некое имя бренда, сверяет его с реестром
# доступных имен и возвращает либо само имя, либо его исправленный вариант, если имя бренда было указано некорректно

def fixBrandNames(brand):
    BRANDS = {'BONECRUSHER':        'BONE CRUSHER',
              'COLDVINE':           'COLD VINE',
              'COLDWINE':           'COLD VINE',
              'COLD WINE':          'COLD VINE',
              'DEDIETRICH':         'DE DIETRICH',
              'DE LONGHI':          'DELONGHI',
              'ELECTRONICS DELUXE': 'ELECTRONICSDELUXE',
              'ELECTRONICS DELUX':  'ELECTRONICSDELUXE',
              'ELECTRONICS DE LUXE':'ELECTRONICSDELUXE',
              'ELECTRONICS DE LUX': 'ELECTRONICSDELUXE',
              'ELECTRONIC DELUX':   'ELECTRONICSDELUXE',
              'ELECTRONIC DELUXE':  'ELECTRONICSDELUXE',
              'ELECTRONIC DE LUX':  'ELECTRONICSDELUXE',
              'ELECTRONIC DE LUXE': 'ELECTRONICSDELUXE',
              'EURO CAVE':          'EUROCAVE',
              'FULGOR':             'FULGOR MILANO',
              'GORENJE +':          'GORENJE+',
              'HOTPOINT':           'HOTPOINT-ARISTON',
              'ARISTON':            'HOTPOINT-ARISTON',
              'INSINK ERATOR':      'IN SINK ERATOR',
              'INSINKERATOR':       'IN SINK ERATOR',
              'INDELB':             'INDEL B',
              'IOMABE':             'IO MABE',
              'MABE':               'IO MABE',
              'IPINDUSTRIE':        'IP INDUSTRIE',
              'IP INDUSTRY':        'IP INDUSTRIE',
              'I-ROBOT':            'IROBOT',
              'I ROBOT':            'IROBOT',
              'JETAIR':             'JET AIR',
              'KITCHENAID':         'KITCHEN AID',
              'LASOMMELIERE':       'LA SOMMELIERE',
              'MITSUBISHI':         'MITSUBISHI ELECTRIC',
              'MITSUBISHIELECTRIC': 'MITSUBISHI ELECTRIC',
              'VZUG':               'V-ZUG',
              'V ZUG':              'V-ZUG',
              'ZUG':                'V-ZUG',
              'VEST FROST':         'VESTFROST',
              'ZIGMUND & SHTAIN':   'ZIGMUND&SHTAIN',
              'ZIGMUND SHTAIN':     'ZIGMUND&SHTAIN',
              'ZIGMUNDSHTAIN':      'ZIGMUND&SHTAIN',
              'ZIGMUND AND SHTAIN': 'ZIGMUND&SHTAIN',
              'Z&S':                'ZIGMUND&SHTAIN'}
    try:    return BRANDS[brand.upper()]
    except: return brand.upper()